a=input("masukan nama :")
b=input("sekolah nang ndi :")
c=input("jurusane opo?:")
d=int(input("masukan nilai ulangan:"))
e=int(input("masukan nilai praktek:"))
f=int(input("masukan nilai harian:"))
print("nama saya adalah:",a)
print("sekolahe kulo nggoneng:",b)
print("jurusane iku :",c)
print("nilai ulangan :",d)
print("nilai praktek :",e)
print("nilai harian:,f")
print("nilai rata rata",(d*e*f)/3)
print("hello word "*3)
